version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5440:5432
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6381:6379
  rails:
    build: .
    command: sh -c 'cd /app/hata && bundle install && rails s -b 0.0.0.0'
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/app/hata
      - hata-gems:/usr/local/bundle
    tty: true
    stdin_open: true
    env_file:
      - .env
  sidekiq:
    build: .
    command: sh -c 'cd /app/hata && sidekiq'
    depends_on:
      - redis

    volumes:
      - .:/app/hata
      - hata-gems:/usr/local/bundle
    tty: true
    stdin_open: true
    env_file:
      - .env
volumes:
  hata-gems:
    driver: local


